networks:
  default:
    external:
      name: dy
services:
  adminer:
    environment:
      - VIRTUAL_HOST=adminer.docky-odoo-template.dy
      - VIRTUAL_PORT=8080
    image: adminer
    links:
      - db
    networks:
      default:
        aliases:
          - adminer.docky-odoo-template.dy
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=docky-odoo-template.dy
      - VIRTUAL_PORT=8069
      - WORKERS=0
      - ADDONS_PATH=/odoo/src/odoo/addons,/odoo/src/addons,/odoo/links,/odoo/local-src
    links:
      - db
      - pgadmin
      - adminer
    networks:
      default:
        aliases:
          - docky-odoo-template.dy
    volumes:
      - ./odoo:/odoo
  pgadmin:
    environment:
      - VIRTUAL_HOST=pgadmin.docky-odoo-template.dy
      - VIRTUAL_PORT=5050
    image: fenglc/pgadmin4
    links:
      - db
    networks:
      default:
        aliases:
          - pgadmin.docky-odoo-template.dy
version: '3'
